# Render Blueprint for Blenvi Monorepo
# Documentation: https://render.com/docs/blueprint-spec
# Monorepo Support: https://render.com/docs/monorepo-support

services:
  # NestJS API Backend
  - type: web
    name: blenvi-api
    runtime: node
    region: oregon # Change to your preferred region
    plan: starter # Change to your preferred plan (free, starter, standard, pro)
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildFilter:
      paths:
        - apps/api/**
        - packages/**
        - package.json
        - package-lock.json
        - turbo.json
    healthCheckPath: /

  # Next.js Web Application
  - type: web
    name: blenvi-web
    runtime: node
    region: oregon # Change to your preferred region
    plan: starter # Change to your preferred plan
    rootDir: apps/web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Add your Supabase environment variables
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false # Set via Render Dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false # Set via Render Dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Set via Render Dashboard
    buildFilter:
      paths:
        - apps/web/**
        - packages/ui/**
        - packages/typescript-config/**
        - packages/eslint-config/**
        - package.json
        - package-lock.json
        - turbo.json
    healthCheckPath: /

  # Documentation Site (Fumadocs)
  - type: web
    name: blenvi-docs
    runtime: node
    region: oregon # Change to your preferred region
    plan: starter # Change to your preferred plan
    rootDir: apps/docs
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    buildFilter:
      paths:
        - apps/docs/**
        - packages/typescript-config/**
        - packages/eslint-config/**
        - package.json
        - package-lock.json
        - turbo.json
    healthCheckPath: /

  # Storybook (Component Library)
  - type: web
    name: blenvi-storybook
    runtime: node
    region: oregon # Change to your preferred region
    plan: starter # Change to your preferred plan
    rootDir: apps/storybook
    buildCommand: npm install && npm run build-storybook
    startCommand: npx http-server storybook-static -p 3002
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
    buildFilter:
      paths:
        - apps/storybook/**
        - packages/ui/**
        - packages/typescript-config/**
        - packages/eslint-config/**
        - package.json
        - package-lock.json
        - turbo.json
    healthCheckPath: /
# Optional: Add databases if needed
# databases:
#   - name: blenvi-postgres
#     region: oregon
#     plan: starter
#     databaseName: blenvi
#     user: blenvi
