import {
  IconBinoculars,
  IconBrandAuth0,
  IconBrandMongodb,
  IconBrandOpenai,
  IconBrandSentry,
  IconBrandStripe,
  IconBrandSupabase,
  IconBrandVercel,
  IconGitFork,
  IconHelp,
  IconSearch,
  IconSettings,
  IconUser,
  IconUsersGroup,
} from '@tabler/icons-react';

export const mockData = {
  user: {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: '/avatar.svg',
  },
  teams: [
    {
      id: '550e8400-e29b-41d4-a716-446655440000',
      name: 'Personal Workspace',
      logo: IconUser,
      plan: 'Free',
      project: [
        {
          id: '67e55044-10b1-426f-9247-bb680e5fe0c8',
          name: 'Project 1',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: 'c2e076d0-716f-44ce-b7d9-aac2c52d9655',
          name: 'Project 2',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: '9f7b5622-eac6-4e6b-91a4-759bb7c0cfd0',
          name: 'Project 3',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
      ],
    },
    {
      id: '63a9f0ea-7bb3-4dfc-8dca-0ed7d9ee3f6c',
      name: 'Team Workspace',
      logo: IconUsersGroup,
      plan: 'Pro',
      project: [
        {
          id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
          name: 'Project 4',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: 'd0ba094b-1b21-4562-a210-3539bca287a6',
          name: 'Project 5',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: '3a3d89b1-a76f-4b3b-a29e-36e2096bf5a1',
          name: 'Project 6',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
      ],
    },
    {
      id: '4d829678-354f-45d8-a336-527bcf7ab45d',
      name: 'Enterprise Workspace',
      logo: IconUsersGroup,
      plan: 'Enterprise',
      project: [
        {
          id: '186c7934-2d16-442f-abc7-f982d8531a60',
          name: 'Project 7',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: 'b426cda8-a51e-4ac2-95e7-599dfb239c1a',
          name: 'Project 8',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
        {
          id: 'e85f8c04-57ce-4964-9689-1a8193212d54',
          name: 'Project 9',
          logo: IconBinoculars,
          plan: 'Free',
          integrations: [
            {
              name: 'Auth0',
              slug: 'auth0',
              icon: IconBrandAuth0,
            },
            {
              name: 'Supabase',
              slug: 'supabase',
              icon: IconBrandSupabase,
            },
            {
              name: 'Stripe',
              slug: 'stripe',
              icon: IconBrandStripe,
            },
            {
              name: 'Vercel',
              slug: 'vercel',
              icon: IconBrandVercel,
            },
            {
              name: 'OpenAI',
              slug: 'openai',
              icon: IconBrandOpenai,
            },
            {
              name: 'MongoDB',
              slug: 'mongodb',
              icon: IconBrandMongodb,
            },
            {
              name: 'Sentry',
              slug: 'sentry',
              icon: IconBrandSentry,
            },
          ],
        },
      ],
    },
  ],
};

export const mockIntegrations = [
  {
    id: '550e8400-e29b-41d4-a716-446655441000',
    slug: 'mongodb',
    name: 'MongoDB',
    description: 'NoSQL Database & Atlas Cloud',
    icon: IconBrandMongodb,
    status: 'connected',
    health: 99,
    color: 'bg-green-500',
    category: 'Database',
    config: {
      connectionString: 'mongodb+srv://username:password@cluster0.mongodb.net/myDatabase',
      databaseName: 'production-db',
      apiKey: '5f7a8b9c0d1e2f3g4h5i6j7k',
      apiSecret: 'mongodb-atlas-api-secret-key-abcdef123456',
      region: 'us-east-1',
      enableCompression: true,
      maxPoolSize: 100,
      connectTimeoutMS: 30000,
      retryWrites: true,
      enableSSL: true,
      readPreference: 'primaryPreferred',
    },
    features: [
      'Document Database',
      'Atlas Search',
      'Data Lake',
      'Realtime Sync',
      'Aggregation Pipeline',
    ],
    webhooks: ['database.created', 'collection.modified', 'backup.completed', 'alert.triggered'],
  },
  {
    id: '63a9f0ea-7bb3-4dfc-8dca-0ed7d9ee3f7d',
    slug: 'auth0',
    name: 'Auth0',
    description: 'Identity & Access Management',
    icon: IconBrandAuth0,
    status: 'connected',
    health: 98,
    color: 'bg-orange-500',
    category: 'Auth',
    config: {
      domain: 'your-tenant.auth0.com',
      clientId: 'AbCd1234XyZ...',
      clientSecret: 'sEcReT-aBcD1234...',
      audience: 'https://api.yourapp.com',
      callbackUrl: 'https://yourapp.com/callback',
      logoutUrl: 'https://yourapp.com/logout',
      enableMFA: true,
      enableSocialLogin: true,
      sessionTimeout: 24,
    },
    features: [
      'Authentication',
      'Social Login',
      'Multi-factor Auth',
      'User Management',
      'Role-based Access',
    ],
    webhooks: ['user.created', 'user.updated', 'user.login', 'user.deleted'],
  },
  {
    id: '7d2fcf34-8e5a-45d1-9a72-c82c1b157788',
    slug: 'supabase',
    name: 'Supabase',
    description: 'Open Source Firebase Alternative',
    icon: IconBrandSupabase,
    status: 'connected',
    health: 96,
    color: 'bg-emerald-600',
    category: 'Backend',
    config: {
      url: 'https://yourproject.supabase.co',
      apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      serviceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      jwtSecret: 'your-jwt-secret',
      project: 'your-project-ref',
      region: 'us-east-1',
      enableRealtime: true,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
    features: ['PostgreSQL Database', 'Authentication', 'Storage', 'Realtime', 'Edge Functions'],
    webhooks: ['auth.signup', 'auth.login', 'storage.upload', 'database.changes'],
  },
  {
    slug: 'sentry',
    name: 'Sentry',
    description: 'Error Tracking & Performance Monitoring',
    icon: IconBrandSentry,
    status: 'connected',
    health: 97,
    color: 'bg-blue-500',
    category: 'Monitoring',
    config: {
      dsn: 'https://1234567890abcdef1234567890abcdef@o123456.ingest.sentry.io/1234567',
      organizationId: 'your-organization',
      projectId: 'your-project',
      authToken: '1234567890abcdef1234567890abcdef1234567890abcdef',
      environment: 'production',
      enableTracing: true,
      sampleRate: 0.5,
      tracesSampleRate: 0.2,
      enablePerformance: true,
      maxBreadcrumbs: 100,
    },
    features: [
      'Error Tracking',
      'Performance Monitoring',
      'Session Replay',
      'Release Health',
      'Distributed Tracing',
    ],
    webhooks: ['issue.created', 'issue.resolved', 'issue.assigned', 'issue.ignored'],
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'Payment Processing',
    icon: IconBrandStripe,
    status: 'connected',
    health: 95,
    color: 'bg-purple-500',
    category: 'Payments',
    config: {
      publishableKey: 'pk_test_...',
      secretKey: 'sk_test_...',
      webhookSecret: 'whsec_...',
      currency: 'usd',
      mode: 'test',
      enableTax: true,
      enablePromotions: true,
      statementDescriptor: 'ACME INC',
    },
    features: ['Payments', 'Subscriptions', 'Invoicing', 'Tax Calculation'],
    webhooks: ['payment_intent.succeeded', 'customer.subscription.created', 'invoice.paid'],
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    description: 'Deployment & Hosting',
    icon: IconBrandVercel,
    status: 'connected',
    health: 99,
    color: 'bg-black',
    category: 'Infrastructure',
    config: {
      token: 'vercel_...',
      teamId: 'team_...',
      projectId: 'prj_...',
      region: 'iad1',
      enableAnalytics: true,
      enableSpeedInsights: true,
      enableWebVitals: true,
    },
    features: ['Hosting', 'Serverless Functions', 'Edge Network', 'Analytics'],
    webhooks: ['deployment.created', 'deployment.ready', 'deployment.error'],
  },
  {
    slug: 'openai',
    name: 'OpenAI',
    description: 'AI & Machine Learning',
    icon: IconBrandOpenai,
    status: 'connected',
    health: 94,
    color: 'bg-emerald-500',
    category: 'AI',
    config: {
      apiKey: 'sk-...',
      organization: 'org-...',
      model: 'gpt-4',
      maxTokens: 4000,
      temperature: 0.7,
      enableModeration: true,
      rateLimitRPM: 3500,
    },
    features: ['Text Generation', 'Chat Completion', 'Embeddings', 'Moderation'],
    webhooks: [],
  },
];

export const navMain = [
  {
    title: 'Overview',
    url: '',
    icon: IconBinoculars,
  },
  {
    title: 'Team',
    url: '/team',
    icon: IconUsersGroup,
  },
  {
    title: 'Workflow',
    url: '/workflow',
    icon: IconGitFork,
  },
];

export const navSecondary = [
  {
    title: 'Settings',
    url: '/settings',
    icon: IconSettings,
  },
  {
    title: 'Get Help',
    url: '/help',
    icon: IconHelp,
  },
  {
    title: 'Search',
    url: '/search',
    icon: IconSearch,
  },
];
