# Netlify Configuration for Storybook
# Documentation: https://docs.netlify.com/build/configure-builds/file-based-configuration/

[build]
  # Build command - only build storybook, skip other apps
  command = "npx turbo run build-storybook --filter=storybook... --filter=!web --filter=!docs --filter=!api --filter=!native"

  # Publish directory relative to repository root
  publish = "apps/storybook/storybook-static"

  # Package directory - where this app's source files are located
  # Set this in Netlify UI: apps/storybook

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "11.6.2"

# Ignore builds - only build when storybook or UI packages change
[build.ignore]
  command = '''
    if [ "$CACHED_COMMIT_REF" = "" ]; then
      echo "First build - building"
      exit 1
    fi

    # Check if storybook or UI packages changed
    git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/storybook packages/ui packages/typescript-config packages/eslint-config package.json turbo.json
  '''

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure SPA routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
